class SkipEmbeddedJavascriptsGenerator < Rails::Generator::Base
  def manifest
    record do |m|
      assets = %w[
        public/blank.html
        public/javascripts/skip_embedded/dropdown_navigation.js
        public/javascripts/skip_embedded/labeled_text_field.js
        public/javascripts/skip_embedded/flash_message.js
        public/javascripts/skip_embedded/iframe_upload.js
        public/javascripts/skip_embedded/ckeditor_config.js
        public/javascripts/skip_embedded/ckeditor/CHANGES.html
        public/javascripts/skip_embedded/ckeditor/LICENSE.html
        public/javascripts/skip_embedded/ckeditor/ckeditor.js
        public/javascripts/skip_embedded/ckeditor/ckeditor.pack
        public/javascripts/skip_embedded/ckeditor/ckeditor_basic.js
        public/javascripts/skip_embedded/ckeditor/ckeditor_basic_source.js
        public/javascripts/skip_embedded/ckeditor/ckeditor_source.js
        public/javascripts/skip_embedded/ckeditor/config.js
        public/javascripts/skip_embedded/ckeditor/contents.css
        public/javascripts/skip_embedded/ckeditor/images/spacer.gif
        public/javascripts/skip_embedded/ckeditor/lang/_languages.js
        public/javascripts/skip_embedded/ckeditor/lang/_translationstatus.txt
        public/javascripts/skip_embedded/ckeditor/lang/af.js
        public/javascripts/skip_embedded/ckeditor/lang/ar.js
        public/javascripts/skip_embedded/ckeditor/lang/bg.js
        public/javascripts/skip_embedded/ckeditor/lang/bn.js
        public/javascripts/skip_embedded/ckeditor/lang/bs.js
        public/javascripts/skip_embedded/ckeditor/lang/ca.js
        public/javascripts/skip_embedded/ckeditor/lang/cs.js
        public/javascripts/skip_embedded/ckeditor/lang/da.js
        public/javascripts/skip_embedded/ckeditor/lang/de.js
        public/javascripts/skip_embedded/ckeditor/lang/el.js
        public/javascripts/skip_embedded/ckeditor/lang/en-au.js
        public/javascripts/skip_embedded/ckeditor/lang/en-ca.js
        public/javascripts/skip_embedded/ckeditor/lang/en-uk.js
        public/javascripts/skip_embedded/ckeditor/lang/en.js
        public/javascripts/skip_embedded/ckeditor/lang/eo.js
        public/javascripts/skip_embedded/ckeditor/lang/es.js
        public/javascripts/skip_embedded/ckeditor/lang/et.js
        public/javascripts/skip_embedded/ckeditor/lang/eu.js
        public/javascripts/skip_embedded/ckeditor/lang/fa.js
        public/javascripts/skip_embedded/ckeditor/lang/fi.js
        public/javascripts/skip_embedded/ckeditor/lang/fo.js
        public/javascripts/skip_embedded/ckeditor/lang/fr-ca.js
        public/javascripts/skip_embedded/ckeditor/lang/fr.js
        public/javascripts/skip_embedded/ckeditor/lang/gl.js
        public/javascripts/skip_embedded/ckeditor/lang/gu.js
        public/javascripts/skip_embedded/ckeditor/lang/he.js
        public/javascripts/skip_embedded/ckeditor/lang/hi.js
        public/javascripts/skip_embedded/ckeditor/lang/hr.js
        public/javascripts/skip_embedded/ckeditor/lang/hu.js
        public/javascripts/skip_embedded/ckeditor/lang/is.js
        public/javascripts/skip_embedded/ckeditor/lang/it.js
        public/javascripts/skip_embedded/ckeditor/lang/ja.js
        public/javascripts/skip_embedded/ckeditor/lang/km.js
        public/javascripts/skip_embedded/ckeditor/lang/ko.js
        public/javascripts/skip_embedded/ckeditor/lang/lt.js
        public/javascripts/skip_embedded/ckeditor/lang/lv.js
        public/javascripts/skip_embedded/ckeditor/lang/mn.js
        public/javascripts/skip_embedded/ckeditor/lang/ms.js
        public/javascripts/skip_embedded/ckeditor/lang/nb.js
        public/javascripts/skip_embedded/ckeditor/lang/nl.js
        public/javascripts/skip_embedded/ckeditor/lang/no.js
        public/javascripts/skip_embedded/ckeditor/lang/pl.js
        public/javascripts/skip_embedded/ckeditor/lang/pt-br.js
        public/javascripts/skip_embedded/ckeditor/lang/pt.js
        public/javascripts/skip_embedded/ckeditor/lang/ro.js
        public/javascripts/skip_embedded/ckeditor/lang/ru.js
        public/javascripts/skip_embedded/ckeditor/lang/sk.js
        public/javascripts/skip_embedded/ckeditor/lang/sl.js
        public/javascripts/skip_embedded/ckeditor/lang/sr-latn.js
        public/javascripts/skip_embedded/ckeditor/lang/sr.js
        public/javascripts/skip_embedded/ckeditor/lang/sv.js
        public/javascripts/skip_embedded/ckeditor/lang/th.js
        public/javascripts/skip_embedded/ckeditor/lang/tr.js
        public/javascripts/skip_embedded/ckeditor/lang/uk.js
        public/javascripts/skip_embedded/ckeditor/lang/vi.js
        public/javascripts/skip_embedded/ckeditor/lang/zh-cn.js
        public/javascripts/skip_embedded/ckeditor/lang/zh.js
        public/javascripts/skip_embedded/ckeditor/plugins/about/dialogs/about.js
        public/javascripts/skip_embedded/ckeditor/plugins/about/dialogs/logo_ckeditor.png
        public/javascripts/skip_embedded/ckeditor/plugins/about/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/basicstyles/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/blockquote/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/button/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/clipboard/dialogs/paste.js
        public/javascripts/skip_embedded/ckeditor/plugins/clipboard/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/colorbutton/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/contextmenu/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/dialog/dialogDefinition.js
        public/javascripts/skip_embedded/ckeditor/plugins/dialog/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/dialogui/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/domiterator/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/editingblock/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/elementspath/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/enterkey/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/entities/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/fakeobjects/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/filebrowser/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/find/dialogs/find.js
        public/javascripts/skip_embedded/ckeditor/plugins/find/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/flash/dialogs/flash.js
        public/javascripts/skip_embedded/ckeditor/plugins/flash/images/placeholder.png
        public/javascripts/skip_embedded/ckeditor/plugins/flash/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/floatpanel/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/font/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/format/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/forms/dialogs/button.js
        public/javascripts/skip_embedded/ckeditor/plugins/forms/dialogs/checkbox.js
        public/javascripts/skip_embedded/ckeditor/plugins/forms/dialogs/form.js
        public/javascripts/skip_embedded/ckeditor/plugins/forms/dialogs/hiddenfield.js
        public/javascripts/skip_embedded/ckeditor/plugins/forms/dialogs/radio.js
        public/javascripts/skip_embedded/ckeditor/plugins/forms/dialogs/select.js
        public/javascripts/skip_embedded/ckeditor/plugins/forms/dialogs/textarea.js
        public/javascripts/skip_embedded/ckeditor/plugins/forms/dialogs/textfield.js
        public/javascripts/skip_embedded/ckeditor/plugins/forms/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/horizontalrule/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/htmldataprocessor/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/htmlwriter/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/iframedialog/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/image/dialogs/image.js
        public/javascripts/skip_embedded/ckeditor/plugins/image/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/indent/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/justify/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/keystrokes/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/link/dialogs/anchor.js
        public/javascripts/skip_embedded/ckeditor/plugins/link/dialogs/link.js
        public/javascripts/skip_embedded/ckeditor/plugins/link/images/anchor.gif
        public/javascripts/skip_embedded/ckeditor/plugins/link/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/list/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/listblock/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/maximize/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/menu/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/menubutton/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/newpage/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/pagebreak/images/pagebreak.gif
        public/javascripts/skip_embedded/ckeditor/plugins/pagebreak/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/panel/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/panelbutton/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/pastefromword/dialogs/pastefromword.js
        public/javascripts/skip_embedded/ckeditor/plugins/pastefromword/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/pastetext/dialogs/pastetext.js
        public/javascripts/skip_embedded/ckeditor/plugins/pastetext/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/popup/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/preview/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/print/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/removeformat/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/resize/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/richcombo/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/save/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/scayt/dialogs/options.js
        public/javascripts/skip_embedded/ckeditor/plugins/scayt/dialogs/toolbar.css
        public/javascripts/skip_embedded/ckeditor/plugins/scayt/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/selection/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/showblocks/images/block_address.png
        public/javascripts/skip_embedded/ckeditor/plugins/showblocks/images/block_blockquote.png
        public/javascripts/skip_embedded/ckeditor/plugins/showblocks/images/block_div.png
        public/javascripts/skip_embedded/ckeditor/plugins/showblocks/images/block_h1.png
        public/javascripts/skip_embedded/ckeditor/plugins/showblocks/images/block_h2.png
        public/javascripts/skip_embedded/ckeditor/plugins/showblocks/images/block_h3.png
        public/javascripts/skip_embedded/ckeditor/plugins/showblocks/images/block_h4.png
        public/javascripts/skip_embedded/ckeditor/plugins/showblocks/images/block_h5.png
        public/javascripts/skip_embedded/ckeditor/plugins/showblocks/images/block_h6.png
        public/javascripts/skip_embedded/ckeditor/plugins/showblocks/images/block_p.png
        public/javascripts/skip_embedded/ckeditor/plugins/showblocks/images/block_pre.png
        public/javascripts/skip_embedded/ckeditor/plugins/showblocks/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/smiley/dialogs/smiley.js
        public/javascripts/skip_embedded/ckeditor/plugins/smiley/images/angel_smile.gif
        public/javascripts/skip_embedded/ckeditor/plugins/smiley/images/angry_smile.gif
        public/javascripts/skip_embedded/ckeditor/plugins/smiley/images/broken_heart.gif
        public/javascripts/skip_embedded/ckeditor/plugins/smiley/images/confused_smile.gif
        public/javascripts/skip_embedded/ckeditor/plugins/smiley/images/cry_smile.gif
        public/javascripts/skip_embedded/ckeditor/plugins/smiley/images/devil_smile.gif
        public/javascripts/skip_embedded/ckeditor/plugins/smiley/images/embaressed_smile.gif
        public/javascripts/skip_embedded/ckeditor/plugins/smiley/images/envelope.gif
        public/javascripts/skip_embedded/ckeditor/plugins/smiley/images/heart.gif
        public/javascripts/skip_embedded/ckeditor/plugins/smiley/images/kiss.gif
        public/javascripts/skip_embedded/ckeditor/plugins/smiley/images/lightbulb.gif
        public/javascripts/skip_embedded/ckeditor/plugins/smiley/images/omg_smile.gif
        public/javascripts/skip_embedded/ckeditor/plugins/smiley/images/regular_smile.gif
        public/javascripts/skip_embedded/ckeditor/plugins/smiley/images/sad_smile.gif
        public/javascripts/skip_embedded/ckeditor/plugins/smiley/images/shades_smile.gif
        public/javascripts/skip_embedded/ckeditor/plugins/smiley/images/teeth_smile.gif
        public/javascripts/skip_embedded/ckeditor/plugins/smiley/images/thumbs_down.gif
        public/javascripts/skip_embedded/ckeditor/plugins/smiley/images/thumbs_up.gif
        public/javascripts/skip_embedded/ckeditor/plugins/smiley/images/tounge_smile.gif
        public/javascripts/skip_embedded/ckeditor/plugins/smiley/images/whatchutalkingabout_smile.gif
        public/javascripts/skip_embedded/ckeditor/plugins/smiley/images/wink_smile.gif
        public/javascripts/skip_embedded/ckeditor/plugins/smiley/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/sourcearea/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/specialchar/dialogs/specialchar.js
        public/javascripts/skip_embedded/ckeditor/plugins/specialchar/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/styles/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/stylescombo/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/stylescombo/styles/default.js
        public/javascripts/skip_embedded/ckeditor/plugins/tab/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/table/dialogs/table.js
        public/javascripts/skip_embedded/ckeditor/plugins/table/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/tabletools/dialogs/tableCell.js
        public/javascripts/skip_embedded/ckeditor/plugins/tabletools/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/templates/dialogs/templates.js
        public/javascripts/skip_embedded/ckeditor/plugins/templates/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/templates/templates/default.js
        public/javascripts/skip_embedded/ckeditor/plugins/templates/templates/images/template1.gif
        public/javascripts/skip_embedded/ckeditor/plugins/templates/templates/images/template2.gif
        public/javascripts/skip_embedded/ckeditor/plugins/templates/templates/images/template3.gif
        public/javascripts/skip_embedded/ckeditor/plugins/toolbar/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/uicolor/dialogs/uicolor.js
        public/javascripts/skip_embedded/ckeditor/plugins/uicolor/lang/en.js
        public/javascripts/skip_embedded/ckeditor/plugins/uicolor/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/uicolor/uicolor.gif
        public/javascripts/skip_embedded/ckeditor/plugins/uicolor/yui/assets/hue_bg.png
        public/javascripts/skip_embedded/ckeditor/plugins/uicolor/yui/assets/hue_thumb.png
        public/javascripts/skip_embedded/ckeditor/plugins/uicolor/yui/assets/picker_mask.png
        public/javascripts/skip_embedded/ckeditor/plugins/uicolor/yui/assets/picker_thumb.png
        public/javascripts/skip_embedded/ckeditor/plugins/uicolor/yui/assets/yui.css
        public/javascripts/skip_embedded/ckeditor/plugins/uicolor/yui/yui.js
        public/javascripts/skip_embedded/ckeditor/plugins/undo/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/wsc/dialogs/ciframe.html
        public/javascripts/skip_embedded/ckeditor/plugins/wsc/dialogs/tmpFrameset.html
        public/javascripts/skip_embedded/ckeditor/plugins/wsc/dialogs/wsc.css
        public/javascripts/skip_embedded/ckeditor/plugins/wsc/dialogs/wsc.js
        public/javascripts/skip_embedded/ckeditor/plugins/wsc/plugin.js
        public/javascripts/skip_embedded/ckeditor/plugins/wysiwygarea/plugin.js
        public/javascripts/skip_embedded/ckeditor/skins/kama/dialog.css
        public/javascripts/skip_embedded/ckeditor/skins/kama/editor.css
        public/javascripts/skip_embedded/ckeditor/skins/kama/icons.png
        public/javascripts/skip_embedded/ckeditor/skins/kama/images/arrowdown.gif
        public/javascripts/skip_embedded/ckeditor/skins/kama/images/arrowleft.gif
        public/javascripts/skip_embedded/ckeditor/skins/kama/images/arrowright.gif
        public/javascripts/skip_embedded/ckeditor/skins/kama/images/arrowtop.gif
        public/javascripts/skip_embedded/ckeditor/skins/kama/images/dialog_sides.gif
        public/javascripts/skip_embedded/ckeditor/skins/kama/images/dialog_sides.png
        public/javascripts/skip_embedded/ckeditor/skins/kama/images/dialog_sides_rtl.png
        public/javascripts/skip_embedded/ckeditor/skins/kama/images/mini.gif
        public/javascripts/skip_embedded/ckeditor/skins/kama/images/noimage.png
        public/javascripts/skip_embedded/ckeditor/skins/kama/images/resizer.gif
        public/javascripts/skip_embedded/ckeditor/skins/kama/images/resizer_rtl.gif
        public/javascripts/skip_embedded/ckeditor/skins/kama/images/sprites.png
        public/javascripts/skip_embedded/ckeditor/skins/kama/images/sprites_ie6.png
        public/javascripts/skip_embedded/ckeditor/skins/kama/images/toolbar_start.gif
        public/javascripts/skip_embedded/ckeditor/skins/kama/skin.js
        public/javascripts/skip_embedded/ckeditor/skins/kama/sprites.png
        public/javascripts/skip_embedded/ckeditor/skins/kama/templates.css
        public/javascripts/skip_embedded/ckeditor/skins/office2003/dialog.css
        public/javascripts/skip_embedded/ckeditor/skins/office2003/editor.css
        public/javascripts/skip_embedded/ckeditor/skins/office2003/icons.png
        public/javascripts/skip_embedded/ckeditor/skins/office2003/images/arrowdown.gif
        public/javascripts/skip_embedded/ckeditor/skins/office2003/images/arrowleft.gif
        public/javascripts/skip_embedded/ckeditor/skins/office2003/images/arrowright.gif
        public/javascripts/skip_embedded/ckeditor/skins/office2003/images/arrowtop.gif
        public/javascripts/skip_embedded/ckeditor/skins/office2003/images/dialog_sides.gif
        public/javascripts/skip_embedded/ckeditor/skins/office2003/images/dialog_sides.png
        public/javascripts/skip_embedded/ckeditor/skins/office2003/images/dialog_sides_rtl.png
        public/javascripts/skip_embedded/ckeditor/skins/office2003/images/mini.gif
        public/javascripts/skip_embedded/ckeditor/skins/office2003/images/noimage.png
        public/javascripts/skip_embedded/ckeditor/skins/office2003/images/resizer.gif
        public/javascripts/skip_embedded/ckeditor/skins/office2003/images/resizer_rtl.gif
        public/javascripts/skip_embedded/ckeditor/skins/office2003/images/sprites.png
        public/javascripts/skip_embedded/ckeditor/skins/office2003/images/sprites_ie6.png
        public/javascripts/skip_embedded/ckeditor/skins/office2003/skin.js
        public/javascripts/skip_embedded/ckeditor/skins/office2003/templates.css
        public/javascripts/skip_embedded/ckeditor/skins/v2/dialog.css
        public/javascripts/skip_embedded/ckeditor/skins/v2/editor.css
        public/javascripts/skip_embedded/ckeditor/skins/v2/icons.png
        public/javascripts/skip_embedded/ckeditor/skins/v2/images/arrowdown.gif
        public/javascripts/skip_embedded/ckeditor/skins/v2/images/arrowleft.gif
        public/javascripts/skip_embedded/ckeditor/skins/v2/images/arrowright.gif
        public/javascripts/skip_embedded/ckeditor/skins/v2/images/arrowtop.gif
        public/javascripts/skip_embedded/ckeditor/skins/v2/images/dialog_sides.gif
        public/javascripts/skip_embedded/ckeditor/skins/v2/images/dialog_sides.png
        public/javascripts/skip_embedded/ckeditor/skins/v2/images/dialog_sides_rtl.png
        public/javascripts/skip_embedded/ckeditor/skins/v2/images/mini.gif
        public/javascripts/skip_embedded/ckeditor/skins/v2/images/noimage.png
        public/javascripts/skip_embedded/ckeditor/skins/v2/images/resizer.gif
        public/javascripts/skip_embedded/ckeditor/skins/v2/images/resizer_rtl.gif
        public/javascripts/skip_embedded/ckeditor/skins/v2/images/sprites.png
        public/javascripts/skip_embedded/ckeditor/skins/v2/images/sprites_ie6.png
        public/javascripts/skip_embedded/ckeditor/skins/v2/images/toolbar_start.gif
        public/javascripts/skip_embedded/ckeditor/skins/v2/skin.js
        public/javascripts/skip_embedded/ckeditor/skins/v2/templates.css
        public/javascripts/skip_embedded/ckeditor/themes/default/theme.js
      ]

      assets.map{|asset| File.dirname(asset) }.uniq.each{|asset| m.directory(asset) }
      assets.each{|asset| m.file asset, asset }
    end
  end
end
